[contest]
name = "nhspc-2021-test"
description = "NHSPC 2021 test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++17 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "barbershop"
title = "barbershop"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "bus"
title = "bus"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "busker"
title = "busker"
time_limit = 2.5
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["2", "1"]

[[tasks]]
name = "car"
title = "car"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]

[[tasks]]
name = "colosseum"
title = "colosseum"
time_limit = 2.5
  [tasks.inclusive_tests]
  3 = ["2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "fruit"
title = "fruit"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "pineapple"
title = "pineapple"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]

[[tasks]]
name = "puipui"
title = "puipui"
time_limit = 2.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "rail"
title = "rail"
time_limit = 0.1
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]
